module.exports = {
 "tt0068646": {
        imdbID: "tt0068646",
        Title: "The Godfather",
        Released: "1972-03-24",
        Runtime: 175,
        Genres: ["Crime", "Drama"],
        Directors: ["Francis Ford Coppola"],
        Writers: ["Mario Puzo", "Francis Ford Coppola"],
        Actors: ["Marlon Brando", "Al Pacino", "James Caan"],
        Plot: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
        Poster: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
        Metascore: 100,
        imdbRating: 9.2
    },
    "tt15398776": {
        imdbID: "tt15398776",
        Title: "Oppenheimer",
        Released: "2023-07-21",
        Runtime: 180,
        Genres: ["Biography", "Drama", "History"],
        Directors: ["Christopher Nolan"],
        Writers: ["Christopher Nolan", "Kai Bird", "Martin Sherwin"],
        Actors: ["Cillian Murphy", "Emily Blunt", "Matt Damon"],
        Plot: "The story of American scientist, J. Robert Oppenheimer, and his role in the development of the atomic bomb.",
        Poster: "https://upload.wikimedia.org/wikipedia/en/4/4a/Oppenheimer_%28film%29.jpg",
        Metascore: 88,
        imdbRating: 8.4
    },
    "tt0993846": {
        imdbID: "tt0993846",
        Title: "The Wolf of Wall Street",
        Released: "2013-12-25",
        Runtime: 180,
        Genres: ["Biography", "Comedy", "Crime"],
        Directors: ["Martin Scorsese"],
        Writers: ["Terence Winter", "Jordan Belfort"],
        Actors: ["Leonardo DiCaprio", "Jonah Hill", "Margot Robbie"],
        Plot: "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_SX300.jpg",
        Metascore: 75,
        imdbRating: 8.2
    },
    "tt0361748": {
        imdbID: "tt0361748",
        Title: "Inglourious Basterds",
        Released: "2009-08-21",
        Runtime: 153,
        Genres: ["Adventure", "Drama", "War"],
        Directors: ["Quentin Tarantino"],
        Writers: ["Quentin Tarantino"],
        Actors: ["Brad Pitt", "Diane Kruger", "Eli Roth"],
        Plot: "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.",
        Poster: "https://upload.wikimedia.org/wikipedia/en/c/c3/Inglourious_Basterds_poster.jpg",
        Metascore: 69,
        imdbRating: 8.3
    },
    "tt4633694": {
        imdbID: "tt4633694",
        Title: "Spider-Man: Into the Spider-Verse",
        Released: "2018-12-14",
        Runtime: 117,
        Genres: ["Animation", "Action", "Adventure"],
        Directors: ["Bob Persichetti", "Peter Ramsey", "Rodney Rothman"],
        Writers: ["Phil Lord", "Rodney Rothman"],
        Actors: ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld"],
        Plot: "Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_SX300.jpg",
        Metascore: 87,
        imdbRating: 8.4
    },
    "tt9362722": {
        imdbID: "tt9362722",
        Title: "Spider-Man: Across the Spider-Verse",
        Released: "2023-06-02",
        Runtime: 140,
        Genres: ["Animation", "Action", "Adventure"],
        Directors: ["Joaquim Dos Santos", "Kemp Powers", "Justin K. Thompson"],
        Writers: ["Phil Lord", "Christopher Miller", "Dave Callaham"],
        Actors: ["Shameik Moore", "Hailee Steinfeld", "Brian Tyree Henry"],
        Plot: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.",
        Poster: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
        Metascore: 86,
        imdbRating: 8.6
    }
};
